### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by davidfowl** [dotnet/crank#9]
- Split repository
  - [x] aspnet/benchmarks
    - We put the benchmark apps here
  - [x] aspnet/perf
    - Infrastructure for benchmarks (driver etc)

- CI/CD
  - Testing
    - [ ] Infrastructure
      - [x] Start two local agents
      - [ ] Docker image and csproj
    - Apps
      - [x] Each app should be tested
  - [ ] Docker image for Agent
  - [x] Global tools (controller + agent)

- Documentation for the infrastructure
  - [x] README
    - [x] New driver only
    - [x] docs, samples
 
- Refactoring
  - Naming
    - [x] Benchmarks Agent
    - [x] Benchmarks Controller
    - [ ] Benchmarks Relay
  - [x] Simpler arguments for Agent when running locally
    - No arguments necessary
    - Automatic available port detection

- Plugins
   - [x] Wrk plugin
   - [x] Bombardier plugin
